% -- Function File: [MU, S] = normalinvwishrnd (MU, KAPPA, NU, LAMBDA)
% -- Function File: [MU, S] = normalinvwishrnd (HYPER)
%     Draw MU from a Normal distribution with parameters MU and KAPPA and draw
%     S from an inverse Wishart distribution with parameters NU and LAMBDA.
%     
%     All arguments can also be fields of HYPER in the form of HYPER.mu, 
%     HYPER.kappa, HYPER.nu, and HYPER.lambda.
%
%     The normalinvishrnd generator can be used to generate the parameters for
%     a Normal distribution (MU, S). The covariance matrix is generated by the
%     inverse Wishart distribution, a probability distribution that is defined
%     on real-valued positive definite matrices. The mean is generated by a 
%     Normal distribution using the incoming argument MU and S scaled by KAPPA
%     as arguments.
%
%     Usage:
%       HYPER.mu = [0 0]'
%       HYPER.kappa = 1
%       HYPER.nu = 2
%       HYPER.lambda = eye(2)
%       [MU, S] = normalinvwishrnd(HYPER)
%
%     See: https://www.wikiwand.com/en/Normal-inverse-Wishart_distribution
%          https://www.wikiwand.com/en/Inverse-Wishart_distribution

function [MU, S] = normalinvwishrnd(arg0, varargin)
	switch (nargin)
	case 1
		mu0 = arg0.mu;
		kappa0 = arg0.kappa;
		nu0 = arg0.nu;
		lambda0 = arg0.lambda;
	case 4
		mu0 = arg0;
		kappa0 = varargin{1};
		nu0 = varargin{2};
		lambda0 = varargin{3};
	otherwise
		warning("The function normalinvwishrnd either has 1 or 4 arguments");
	end

	% Sample S, the covariance matrix, from an inverse Wishart distribution
	S = invwishrnd(nu0,lambda0);
	
	% Sample MU from a normal distribution with covariance S scaled by KAPPA
	MU = mu0 + chol(S/kappa0)' * randn(length(mu0),1);

	if ~(size_equal(mu0, MU))
		warning("Input argument MU is probably not ordered as a single column");
	end
end
